spring:
  datasource:
    url: jdbc:mysql://192.168.126.131:3306/12306?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
