spring:
  datasource:
    url: jdbc:mysql://192.168.126.131:3306/12306?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root

  data:  
    redis:
      host: 192.168.126.131
      port: 6379
      password: 123456
    
  